name: CI/CD Pipeline

on:
  push:
    branches: [ "assignment-02" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: CI-CD   #Doppler

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 sync dist/ s3://$BUCKET_NAME --delete 
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

     - name: Invalidate CloudFront cache
       run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
       env:
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
